# Generated by Django 2.2 on 2020-11-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rtapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(default='', max_length=200)),
                ('testmode', models.CharField(default='', max_length=200)),
                ('scandatetime', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
